class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror@Sprittorbot'
        self.UnzipMirrorCommand = 'unzip@Sprittorbot'
        self.TarMirrorCommand = 'tar@Sprittorbot'
        self.CancelMirror = 'cancel@Sprittorbot'
        self.CancelAllCommand = 'cnlall@Sprittorbot'
        self.ListCommand = 'list@Sprittorbot'
        self.StatusCommand = 'status@Sprittorbot'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stat'
        self.HelpCommand = 'hlp'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest@Sprittorbot'
        self.CloneCommand = 'clone@Sprittorbot'
        self.WatchCommand = 'watch@Sprittorbot'
        self.TarWatchCommand = 'tarwatch@Sprittorbot'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage@Sprittorbot'
        self.RepoCommand = 'repo'

BotCommands = _BotCommands()
